image: jelaniwoods/appdev2021-msm-signin:latest

tasks:
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9515
    onOpen: ignore


vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - vscode.ruby
